package de.hahn.blog.execwithparams.model.common;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 06 08:15:30 CET 2019
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    Timestamp getpDate();

    String getpMail();

    String getpName();

    void setpDate(Timestamp value);

    void setpMail(String value);

    void setpName(String value);

    BigDecimal getpSalary();

    void setpSalary(BigDecimal value);
}

